package ai.yarmook.shipperfinder.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LanguagesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguagesAllPropertiesEquals(Languages expected, Languages actual) {
        assertLanguagesAutoGeneratedPropertiesEquals(expected, actual);
        assertLanguagesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguagesAllUpdatablePropertiesEquals(Languages expected, Languages actual) {
        assertLanguagesUpdatableFieldsEquals(expected, actual);
        assertLanguagesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguagesAutoGeneratedPropertiesEquals(Languages expected, Languages actual) {
        assertThat(actual)
            .as("Verify Languages auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguagesUpdatableFieldsEquals(Languages expected, Languages actual) {
        assertThat(actual)
            .as("Verify Languages relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguagesUpdatableRelationshipsEquals(Languages expected, Languages actual) {
        // empty method
    }
}
