package ai.yarmook.shipperfinder.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TripMsgAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripMsgAllPropertiesEquals(TripMsg expected, TripMsg actual) {
        assertTripMsgAutoGeneratedPropertiesEquals(expected, actual);
        assertTripMsgAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripMsgAllUpdatablePropertiesEquals(TripMsg expected, TripMsg actual) {
        assertTripMsgUpdatableFieldsEquals(expected, actual);
        assertTripMsgUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripMsgAutoGeneratedPropertiesEquals(TripMsg expected, TripMsg actual) {
        assertThat(actual)
            .as("Verify TripMsg auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripMsgUpdatableFieldsEquals(TripMsg expected, TripMsg actual) {
        assertThat(actual)
            .as("Verify TripMsg relevant properties")
            .satisfies(a -> assertThat(a.getMsg()).as("check msg").isEqualTo(expected.getMsg()))
            .satisfies(a -> assertThat(a.getFromUserEncId()).as("check fromUserEncId").isEqualTo(expected.getFromUserEncId()))
            .satisfies(a -> assertThat(a.getToUserEncId()).as("check toUserEncId").isEqualTo(expected.getToUserEncId()))
            .satisfies(a -> assertThat(a.getTripId()).as("check tripId").isEqualTo(expected.getTripId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripMsgUpdatableRelationshipsEquals(TripMsg expected, TripMsg actual) {
        // empty method
    }
}
